# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: N2JjMjcyMDVkOTk4YjFlOTk4Yzg0YTI0Mjk0NzNjYWYwYmY5NzBkMTI0Zjk5NDYyOWRiNzUyYzNiNTMxMTkxMWViMjc3ZDNhYWViZDhkZmJhMTYyM2NlYWE0Y2ZkYWQwNWI0ZDE4YjhhMDA3MjM2MTcxNzBlMDU0MmM5NWE5MDA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
